ALTER TABLE CAMINHOS ADD COLUMN ID_ASPIRACAO VARCHAR(2) NOT NULL;

ALTER TABLE CAMINHOS ADD CONSTRAINT CE_ASPIRACAO_CAMINHO
FOREIGN KEY (ID_ASPIRACAO)
REFERENCES ASPIRACOES (ID_ASPIRACAO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;