ALTER TABLE CAMINHOS ADD COLUMN ID_ASPIRACAO VARCHAR(2) NOT NULL;

ALTER TABLE CAMINHOS ADD CONSTRAINT CE_ASPIRACAO_CAMINHO
FOREIGN KEY (ID_ASPIRACAO)
REFERENCES ASPIRACOES (ID_ASPIRACAO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE HABILIDADES_INTRINSECAS ADD CONSTRAINT CE_CAMINHO_INTRINSECA
FOREIGN KEY (ID_CAMINHO)
REFERENCES CAMINHOS (ID_CAMINHO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE HABILIDADES ADD CONSTRAINT CE_CAMINHO_HABILIDADE
FOREIGN KEY (ID_CAMINHO)
REFERENCES CAMINHOS (ID_CAMINHO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE ARMAS ADD CONSTRAINT CE_EQUIPAMENTO_ARMA
FOREIGN KEY (ID_EQUIPAMENTO)
REFERENCES EQUIPAMENTOS (ID_EQUIPAMENTO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE ARMADURAS ADD CONSTRAINT CE_EQUIPAMENTO_ARMADURA
FOREIGN KEY (ID_EQUIPAMENTO)
REFERENCES EQUIPAMENTOS (ID_EQUIPAMENTO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;