CREATE TABLE ESCOLAS (
ID_ESCOLA VARCHAR(2) NOT NULL PRIMARY KEY,
NOME_ESCOLA VARCHAR(50) NOT NULL
);

CREATE TABLE RACAS (
ID_RACA VARCHAR(3) NOT NULL PRIMARY KEY,
NOME_RACA VARCHAR(20) NOT NULL,
NOME_HABILIDADE VARCHAR(50) NOT NULL,
DESCRICAO_HABILIDADE TEXT NOT NULL,
NOME_RESTRICAO VARCHAR(50) NOT NULL,
DESCRICAO_RESTRICAO TEXT NOT NULL
);

CREATE TABLE ASPIRACOES (
ID_ASPIRACAO VARCHAR(2) NOT NULL PRIMARY KEY,
NOME_ASPIRACAO VARCHAR(15) NOT NULL
);

CREATE TABLE CAMINHOS (
ID_CAMINHO VARCHAR(3) NOT NULL PRIMARY KEY,
NOME_CAMINHO VARCHAR(50) NOT NULL,
TIER TINYINT NOT NULL,
MAESTRIA VARCHAR(150) NOT NULL,
REQUISITOS VARCHAR(150) NOT NULL
);

CREATE TABLE HABILIDADES_INTRINSECAS (
ID_HABILIDADE VARCHAR(6) NOT NULL PRIMARY KEY,
NOME_HABILIDADE VARCHAR(50) NOT NULL,
DESCRICAO TEXT NOT NULL,
ID_CAMINHO VARCHAR(3) NOT NULL
);

CREATE TABLE HABILIDADES (
ID_HABILIDADE VARCHAR(6) NOT NULL PRIMARY KEY,
NOME_HABILIDADE VARCHAR(50) NOT NULL,
CATEGORIA VARCHAR(15) NOT NULL,
DESCRICAO TEXT NOT NULL,
CUSTO INTEGER NOT NULL,
ID_CAMINHO VARCHAR(3) NOT NULL
);

CREATE TABLE ACESSORIOS (
ID_ACESSORIO VARCHAR(6) NOT NULL PRIMARY KEY,
NOME_ACESSORIO VARCHAR(50) NOT NULL,
EFEITO TEXT NOT NULL
);

CREATE TABLE EQUIPAMENTOS (
ID_EQUIPAMENTO VARCHAR(6) NOT NULL PRIMARY KEY,
NOME_EQUIPAMENTO VARCHAR(50) NOT NULL,
CATEGORIA VARCHAR(30) NOT NULL,
EFEITO TEXT NOT NULL
);

CREATE TABLE ARMAS (
ID_EQUIPAMENTO VARCHAR(6) NOT NULL PRIMARY KEY,
DANO VARCHAR(10) NOT NULL,
ACERTO VARCHAR(10) NOT NULL,
ARTES VARCHAR(10) NOT NULL
);

CREATE TABLE ARMADURAS (
ID_EQUIPAMENTO VARCHAR(6) NOT NULL PRIMARY KEY,
ESQUIVA VARCHAR(10) NOT NULL,
DEFESA VARCHAR(10) NOT NULL,
RESISTENCIA VARCHAR (10) NOT NULL,
PV VARCHAR(10) NOT NULL
);

CREATE TABLE PERSONAGENS (
ID_PERSONAGEM INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
DETALHES JSON NOT NULL
);
